/*
 * This source file was generated by the Gradle 'init' task
 */
package linkedlist;

public class App {
    public static void main(String[] args) {

       JunaLinkedList list = new JunaLinkedList();
       list.tambahDepan(30);
    }
}
