/*
 * This source file was generated by the Gradle 'init' task
 */
package linkedlist;

public class App {
    public static void main(String[] args) {

       JunaLinkedList list = new JunaLinkedList();
       list.tambahDepan(10);
       list.cetakList();

       list.tambahBelakang(111);
       list.cetakList();

       list.tambahBelakang(222);
       list.cetakList();
    }
}
